### ISSUE TITLE
More Detailed readme

### ISSUE THREAD

**Issue by Smevy** [ethanaobrien/Gamepad#2]
The Readme is great but you could possibly make a how to setup and use becuase with emulatorjs it was strait forward but this do I add the js file or you should try to specify what to do

**Comment by ethanaobrien** [comment]
It's built into emulatorjs...

**Comment by Smevy** [comment]
sorry I meant the readme in emulator js and the website that teaches you everything

**Comment by ethanaobrien** [comment]
Oh ok, I'll get that written for this one. All you do is download the `gamepad.js` file and reference it through a script tag

**Comment by Smevy** [comment]
ok thank you

**Comment by ethanaobrien** [comment]
Done

**Comment by Smevy** [comment]
thanks
