### ISSUE TITLE
Buttons default to pressed

### ISSUE THREAD

**Issue by Ramaerel** [ethanaobrien/Gamepad#3]
Tested across multiple devices and gamepads-
It seems that the default state of all buttons is pressed, and all inputs are inversed (Pushing the physical button = button becomes unpressed in game, letting go of physical button = pressed in game again)

**Comment by ethanaobrien** [comment]
Oh wait, I thought you meant the delay in the press. Does that still happen?

**Comment by ethanaobrien** [comment]
@Ramaerel This was an issue that was fixed right?

**Comment by Ramaerel** [comment]
Yes, sorry. Forgot we opened an issue here.
